import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_HOST: z.string().min(1),
    DATABASE_USERNAME: z.string().min(1),
    DATABASE_PASSWORD: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    DISCORD_CLIENT_SECRET: z.string().min(1),
    DISCORD_CLIENT_ID: z.string().min(1),
    DISCORD_AUTH_URL: z.string().min(1),
    NEXTAUTH_SECRET: z.string().min(1),
    NODE_ENV: z.enum(["development", "production", "test"]),
    RESEND_KEY: z.string().min(1),
    S3_BUCKET_NAME: z.string().min(1),
    S3_BUCKET_REGION: z.string().min(1),
    S3_BUCKET_ACCESS_KEY: z.string().min(1),
    S3_BUCKET_SECRET_KEY: z.string().min(1),
    APP_ID: z.string().min(1),
    APP_SECRET: z.string().min(1),
    APP_KEY: z.string().min(1),
    APP_CLUSTER: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_CLOUD_ORIGIN: z.string().min(1),
    NEXT_PUBLIC_APP_KEY: z.string().min(1),
    NEXT_PUBLIC_APP_CLUSTER: z.string().min(1),
  },
  runtimeEnv: {
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    DATABASE_HOST: process.env.DATABASE_HOST,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    DATABASE_USERNAME: process.env.DATABASE_USERNAME,
    DATABASE_URL: process.env.DATABASE_URL,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    NODE_ENV: process.env.NODE_ENV,
    DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
    DISCORD_AUTH_URL: process.env.DISCORD_AUTH_URL,
    RESEND_KEY: process.env.RESEND_KEY,
    S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
    S3_BUCKET_REGION: process.env.S3_BUCKET_REGION,
    S3_BUCKET_ACCESS_KEY: process.env.S3_BUCKET_ACCESS_KEY,
    S3_BUCKET_SECRET_KEY: process.env.S3_BUCKET_SECRET_KEY,
    NEXT_PUBLIC_CLOUD_ORIGIN: process.env.NEXT_PUBLIC_CLOUD_ORIGIN,
    APP_ID: process.env.APP_ID,
    APP_SECRET: process.env.APP_SECRET,
    APP_KEY: process.env.APP_KEY,
    APP_CLUSTER: process.env.APP_CLUSTER,
    NEXT_PUBLIC_APP_KEY: process.env.NEXT_PUBLIC_APP_KEY,
    NEXT_PUBLIC_APP_CLUSTER: process.env.NEXT_PUBLIC_APP_CLUSTER,
  },
});
